version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    restart: unless-stopped
    
    env_file:
      - ./.env
      
    ports:
      - "5001:5001"
      
    volumes:
      - ./data:/app/data

networks:
  default:
    driver: bridge
